name: df_builder
description: small package to generate code in a simple way
version: 0.0.2
homepage: https://github.com/FlutterQueen/df_builder
issue_tracker: https://github.com/FlutterQueen/df_builder/issues

environment:
  sdk: ">=2.12.4 <3.0.0"

dependencies:
  equatable: ^2.0.3
  recase: ^4.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
